# 微信公众平台配置
# 使用环境变量 ${VAR_NAME} 格式
WECHAT:
  app_id: ${WECHAT_APP_ID}  # 从环境变量读取
  app_secret: ${WECHAT_APP_SECRET}  # 从环境变量读取从环境变量读取we

# 路径配置
paths:
  watch_dir: ${WATCH_DIR}  # 监控的文档目录
  image_dir: ${IMAGE_DIR}     # 图片目录

# 定义所有要管理的公众号账户
# 这里的键名必须与 a) .env中的变量名 和 b) documents下的文件夹名 完全对应
accounts:
  AI流习社:
    author: "AI流习社" # 可选，覆盖全局默认作者
  开源智核:
    author: "开源智核"
  码趣逻辑站:
    author: "码趣逻辑站"

# 发布配置
publish:
  default_author: "自动发布"
  show_cover: 1  # 是否显示封面图
  
# 监控配置
watch:
  recursive: true  # 是否监控子目录
  file_types: [".md", ".markdown"]  # 监控的文件类型
